name: Remote build App on server

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./cmd/app/main.go
      - name: Test with the Go CLI
        run: go test ./internal/...
